package com.zoho.crm.feature.entityparser.constants

import java.util.regex.Pattern

object UnWantedElements extends Enumeration {

  final val UNWANTEDELEMENTS = "unwantedelements"
  final val GOOD_IRI_CHAR =
    "a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF"

  final val IP_ADDRESS = Pattern.compile(
    "((25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9])\\.(25[0-5]|2[0-4]" +
      "[0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(25[0-5]|2[0-4][0-9]|[0-1]" +
      "[0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}" +
      "|[1-9][0-9]|[0-9]))")

  private final val IRI = "[" + GOOD_IRI_CHAR + "]([" + GOOD_IRI_CHAR + "\\-]{0,61}[" + GOOD_IRI_CHAR + "]){0,1}";

  private final val GOOD_GTLD_CHAR =
    "a-zA-Z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF";
  private final val GTLD = "[" + GOOD_GTLD_CHAR + "]{2,63}";
  private final val HOST_NAME = "(" + IRI + "\\.)+" + GTLD;
  final val DOMAIN_NAME = Pattern.compile("(" + HOST_NAME + "|" + IP_ADDRESS + ")")
  final val WEBSITE = Pattern.compile(
        "((?:(http|https|Http|Https|rtsp|Rtsp):\\/\\/(?:(?:[a-zA-Z0-9\\$\\-\\_\\.\\+\\!\\*\\'\\(\\)"
        + "\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,64}(?:\\:(?:[a-zA-Z0-9\\$\\-\\_"
        + "\\.\\+\\!\\*\\'\\(\\)\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,25})?\\@)?)?"
        + "(?:" + DOMAIN_NAME + ")"
        + "(?:\\:\\d{1,5})?)" // plus option port number
        + "(\\/(?:(?:[" + GOOD_IRI_CHAR + "\\;\\/\\?\\:\\@\\&\\=\\#\\~"  // plus option query params
        + "\\-\\.\\+\\!\\*\\'\\(\\)\\,\\_])|(?:\\%[a-fA-F0-9]{2}))*)?"
        + "(?:\\b|$)")
 final val EMAIL = Pattern.compile(
            "[a-zA-Z0-9\\+\\.\\_\\%\\-\\+]{1,256}" +
            "\\@" +
            "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}" +
            "(" +
                "\\." +
                "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25}" +
            ")?+"
        )
 final val REMOVEQUOTES = "^\"|\"$"
 final val SOCIALMEDIA = Array[String]("facebook","google" , "whatsapp", "messenger", "linkedin", "google+", "twitter", "instagram", "pinterest", "snapchat",
  "quora", "girlsaskguys", "nextdoor", "producthunt", "angellist", "kickstarter", "wechat", "skype", "viber",
  "tumblr", "line", "gab", "vk", "reddit", "telegram", "tagged", "myspace", "badoo", "stumbleupon", "foursquare",
  "meetme", "meetup", "skyrock", "pinboard", "kiwibox", "twoo", "yelp", "snapfish", "flickr", "photobucket", "shutterfly",
  "500px", "deviantart", "dronestagram", "fotki", "fotolog", "imgur", "pixabay", "weheartit", "43things", "path", "uplike",
  "last.fm", "vampirefreaks", "cafemom", "ravelry", "asmallworld", "reverbnation", "soundcloud", "cross.tv", "flixster", "gaia online", "blackplanet",
  "mymfb", "care2", "caringbridge", "gofundme", "tinder", "crokes", "goodreads", "internations", "plentyoffish", "minds", "nexopia",
  "glocals", "academia.edu ", "busuu", "english baby", "italki.com", "untappd", "doximity", "wayn", "couchsurfing", "travbuddy", "tournac",
  "cellufun", "mocospace", "zynga", "habbo", "youtube", "funnyordie", "tout", "vine", "classmates", "myheritage", "23andme",
  "ancestry.com", "viadeo", "ryze", "xing", "sprybirds", "solaborate", "etoro", "xanga", "plurk", "livejournal", "lastfm", "last", "crosstv",
  "cross", "academia", "italki", "ancestry","blog").map(_.toLowerCase.trim).sortWith( _.length > _.length )

 final val CONTACT_LABELS = Array[String]("fax", "no", "phone", "telephone", "tel",
  "email", "mail", "mailto", "call", "mobile",
  "mobileno", "faxno", "phoneno", "tele", "mobilephone",
  "address", "website", "direct","office","company",
  "t:","web site","cell","cellphone","mob","com","e:","a:","f:","web","site","e-mail:", "vist us at:", "vist us:", "id", "email",
  "ph:", "m:", "mobile:", "fax:", "no:", "phone:", "telephone:", "tel:", "webpage:").map(_.toLowerCase.trim).sortWith( _.length > _.length )

 final val ROLEBASED_EMAIL = Array[String]("2015", "2016", "2017", "2018", "2019", "2020", "abuse", "academy", "accessibility", "account",
  "accountant", "accounting", "accountmanagers", "accounts", "accountspayable", "acquisition", "admin1", "administracao", "administrador", "administratie",
  "administratif", "administrativo", "administrator", "administrators", "admins", "adminteam", "admissions", "adops", "ads", "adventure",
  "advertise", "advertising", "advertisingsales", "advice", "advisors", "adwords", "affiliate", "affiliates", "agence", "agencia",
  "agency", "agents", "alarm", "alarms", "alert", "alerts", "all-employees", "all-pms", "all-staff", "all-team",
  "all-users", "all.employees", "all.staff", "all.users", "all_staff", "alla", "alle", "allemployees", "allhands", "allsales",
  "allstaff", "allstudents", "allteachers", "allteam", "allusers", "alpha", "alphas", "alumni", "ambassadors", "amministrazione",
  "analysts", "analytics", "android", "angels", "animation", "announce", "announcements", "ap", "api", "app",
  "apple", "application", "applications", "apply", "appointments", "apps", "archives", "asistente", "asset", "assistanthead",
  "assistencia", "assistenza", "associates", "associates-all", "ateam", "atencionalcliente", "atendimento", "auctions", "backend", "backend-dev",
  "backup", "bd", "benefits", "berlin", "bestellung", "beta", "biblioteca", "bibliotheque", "bills", "biuro",
  "biz", "bizdev", "blog", "board", "bod", "bookclub", "booking", "bookings", "boston", "boxoffice",
  "brand", "branding", "brands", "brandsolutions", "broadcast", "buchhaltung", "bugs", "build", "business", "business_team",
  "businessdevelopment", "ca", "caltrain", "campaign", "campaigns", "campusteam", "capacitacion", "captain", "captains", "care",
  "career", "careers", "catering", "central", "centro", "ceos", "channel-sales", "chat", "chatter", "chef",
  "chicago", "china", "citymanagers", "classof2016", "classof2017", "classof2018", "classof2019", "classroom_teachers", "client", "clientes",
  "clients", "clientservices", "clinic", "cloud", "cm", "coach", "coaches", "coaching", "code", "colaboradores",
  "colegio", "com", "comenzi", "comercial", "comercial1", "comercial2", "comments", "commercial", "commerciale", "commissions",
  "committee", "comms", "communication", "communications", "company", "company.wide", "competition", "compliance", "compras", "compta",
  "comptabilite", "comunicacao", "comunicacion", "comunicaciones", "comunicazione", "concierge", "conference", "connect", "consultas", "consulting",
  "consultoria", "contabil", "contabilidad", "contabilidade", "contabilita", "contactenos", "contactus", "contador", "contato", "content",
  "contractor", "contractors", "contracts", "controller", "coordinator", "copyright", "core", "coreteam", "corp", "corporate",
  "corporatesales", "council", "courrier", "creative", "crm", "cs", "csm", "csteam", "cultura", "culture",
  "customer", "customer.service", "customerfeedback", "customers", "customerservicecenter", "customerservices", "customersuccess", "customersupport", "custserv", "daemon",
  "database", "deals", "delivery", "demo", "denver", "departures", "deploy", "deputy", "deputyhead", "designer",
  "designers", "dev", "developer", "developers", "development", "devnull", "devops", "devs", "devteam", "digital",
  "direccion", "direction", "diretoria", "direzione", "discuss", "dispatch", "diversity", "dns", "docs", "domain",
  "domainmanagement", "domains", "dreamteam", "ecommerce", "education", "einkauf", "email", "emergency", "employee", "employees",
  "employment", "eng", "eng-all", "engagement", "engineering", "engineers", "english", "enquires", "enterprise", "equipe",
  "equipo", "error", "errors", "escritorio", "europe", "event", "events", "everybody", "execs", "execteam",
  "expenses", "facilities", "facturacion", "faculty", "family", "farmacia", "faturamento", "fax", "fbl", "feedback",
  "fellows", "finance", "financeiro", "financeiro2", "finanzas", "firmapost", "fiscal", "food", "football", "founders",
  "france", "franchise", "friends", "frontdesk", "frontend", "frontoffice", "fte", "ftp", "fulltime", "fun",
  "fundraising", "gardner", "geeks", "general", "geral", "global", "grants", "graphics", "group", "growth",
  "hackathon", "hackers", "heads", "hello", "help", "helpdesk", "hi", "highschool", "hiring", "hola",
  "home", "homes", "hosting", "hotel", "house", "hq", "hrdept", "hsstaff", "hsteachers", "humanresources",
  "ideas", "implementation", "import", "inbound", "inbox", "india", "info","infor", "informacion", "informatica", "informatique",
  "infra", "infrastructure", "ingenieria", "innovation", "inoc", "inquiries", "inquiry", "insidesales", "insights", "instagram",
  "insurance", "integration", "integrations", "intern", "internal", "international", "internet", "interns", "internship", "invest",
  "investment", "investor", "investors", "invoice", "invoices", "invoicing", "ios", "iphone", "ir", "ispfeedback",
  "ispsupport", "it", "ithelp", "itsupport", "itunes", "jira", "job", "join", "jornalismo", "junk",
  "kontakt", "kundeservice", "la", "lab", "laboratorio", "labs", "ladies", "latam", "launch", "lead",
  "leaders", "leadership", "leadership-team", "leadershipteam", "leads", "leasing", "legal", "letters", "library", "licensing",
  "links", "list", "list-request", "login", "logistica", "logistics", "logistiek", "lt", "lunch", "mail",
  "mailbox", "maildaemon", "mailer-daemon", "mailerdaemon", "mailing", "maintenance", "management", "management-group", "management.team", "management_team",
  "manager", "managers", "marketing-ops", "marketing-team", "marketingteam", "marketplace", "mayor", "md", "meetup", "member",
  "members", "membership", "mentors", "metrics", "mgmt", "middleschool", "misc", "mkt", "mktg", "mobile",
  "monitor", "monitoring", "montreal", "msstaff", "msteachers", "mt", "music", "network", "newbiz", "newbusiness",
  "news", "newsletter", "newyork", "nntp", "no-reply", "no.replay", "no.reply", "nobody", "noc", "none",
  "noreply", "noresponse", "northamerica", "nospam", "notes", "notifications", "notify", "nps", "null", "ny",
  "nyc", "nyoffice", "offboarding", "offers", "officemanager", "officers", "officestaff", "offtopic", "oficina", "onboarding",
  "online", "onsite", "ooo", "operaciones", "ops", "order", "orders", "ordini", "outage", "outreach",
  "owners", "parents", "paris", "partner", "partners", "partnerships", "parts", "pay", "payment", "payments",
  "paypal", "payroll", "pd", "people", "peoplemanagers", "peopleops", "performance", "personnel", "phish", "phishing",
  "photos", "planning", "platform", "pm", "portfolio", "post", "postbox", "postfix", "postmaster", "ppc",
  "pr", "prefeitura", "presales", "presidencia", "president", "presidente", "press", "presse", "principals", "privacy",
  "procurement", "prod", "produccion", "product", "product-team", "product.growth", "product.management", "product.managers", "product.team", "production",
  "productmanagers", "products", "productteam", "produto", "program", "programs", "project", "projectmanagers", "projects", "promo",
  "promotions", "protocollo", "proveedores", "publicidade", "publisher", "publishers", "purchase", "purchases", "purchasing", "qa",
  "qualidade", "questions", "quotes", "random", "realestate", "receipts", "recepcion", "receptionist", "recruiter", "recruiters",
  "recruitment", "recrutement", "recursoshumanos", "redacao", "redaccion", "redaction", "redazione", "referrals", "register", "registrar",
  "registration", "relacionamento", "release", "releases", "remote", "remove", "rentals", "report", "reporting", "reports",
  "requests", "research", "reservaciones", "reservas", "reservation", "reservations", "residents", "response", "restaurant", "resume",
  "resumes", "retail", "returns", "revenue", "rezervari", "rfp", "rnd", "rockstars", "root", "rrhh",
  "rsvp", "sales-team", "sales.team", "sales1", "sales2", "salesengineers", "salesforce", "salesops", "salesteam", "sanfrancisco",
  "science", "sdr", "se", "search", "seattle", "secretaria", "secretariaat", "secretaris", "sekretariat", "sem",
  "seniors", "seo", "server", "service", "serviceclient", "servicedesk", "services", "servicioalcliente", "sf", "sf-office",
  "sfo", "sfoffice", "sfteam", "shareholders", "shipping", "shop", "shopify", "shopping", "signup", "signups",
  "singapore", "sistemas", "site", "smtp", "social", "socialclub", "socialmedia", "socios", "software", "solutions",
  "soporte", "sos", "spam", "sponsorship", "sport", "squad", "staff", "startups", "stats", "stockholm",
  "store", "stories", "strategy", "stripe", "student", "students", "studio", "submissions", "submit", "subscribe",
  "subscriptions", "success", "suggestions", "supervisor", "supervisors", "suporte", "supply", "support", "support-team", "supportteam",
  "suprimentos", "sydney", "sysadmin", "system", "systems", "ta", "talent", "tax", "teachers", "team",
  "teamleaders", "teamleads", "tech", "technical", "technik", "technology", "techops", "techsupport", "techteam", "tecnologia",
  "tesoreria", "test", "testgroup", "testing", "the.principal", "theteam", "tickets", "time", "timesheets", "todos",
  "tools", "tour", "trade", "trainers", "training", "transport", "travel", "treasurer", "tribe", "trustees",
  "turismo", "twitter", "uk", "undisclosed-recipients", "unsubscribe", "update", "updates", "us", "usa", "user",
  "usteam", "uucp", "ux", "vendas", "vendas1", "vendas2", "vendor", "vendors", "ventas", "ventas1",
  "ventas2", "verkauf", "verwaltung", "video", "vip", "voicemail", "volunteer", "volunteers", "vorstand", "warehouse",
  "watercooler", "web", "webadmin", "webdesign", "webdev", "webinars", "webmaster", "website", "webteam", "welcome",
  "whois", "wholesale", "women", "wordpress", "work", "workshop", "writers", "www", "zentrale")

 val DISPOSBALE_EMAIL = Array[String]("0-mail", "001.igg", "0039", "02466", "027168", "03-genkzmail", "07819", "0815", "0845", "0box", "0clickemail", "0mixmail", "0sg", "0u", "0v", "0w", "0wnd", "0x00", "0x207", "1-8", "1000rebates", "100likers", "101price", "10host", "10launcheds", "10mail", "10minut.com", "10minut", "10minutemail", "10minutemail.co", "10minutemailbox", "10minutemails", "10minutenemail", "10minutesmail", "10minutmail", "10vpn", "10x", "10x9", "117.yyolf", "11top", "123-m", "12ab", "12hosting", "12houremail", "12minutemail", "12storage", "139", "140unichars", "147", "14n.co", "15qm-mail", "15qm", "19922", "1ce", "1chuan", "1clck2", "1dmedical", "1drive", "1fsdfdsfsdf", "1lv", "1mail", "1pad", "1rentcar", "1s", "1ss.noip", "1st-forms", "1to1mail", "1up.orangotango", "1usemail", "1webmail", "1zhuan", "2-ch", "2.emailfake", "2000rebates", "2012-2016", "2014mail", "2018-12-23", "20boxme", "20email", "20mail", "20minute", "20minutemail", "20mm", "2120001", "21lr12", "225522", "24hourmail", "291.usa", "2and2mail", "2ch.coms", "2ch.daemon", "2ch.orgs", "2ether", "2fdgdfgdfgdf", "2kpda46zg", "2prong", "2sea", "2viewerl", "2wc", "300book",
  "30minutemail", "30minutenmail", "30wave", "33m", "33mail", "3675.mooo", "36ru", "3d-painting", "3ew.usa", "3l6", "3mail", "3trtretgfrfe", "4-n", "4.fackme", "418", "41v1relaxn", "420blaze", "42o", "44556677.igg", "466453.usa", "487.nut", "4gfdsgfdgfd", "4mail", "4nmv", "4pet", "4tb", "4w", "4warding", "50mb", "510520", "54np", "555gmail", "55hosting", "5dsmartstore", "5ghgfhfghfgh", "5gramos", "5july", "5mail", "5music", "5oz", "5x25", "5yk.idea-makers", "5ymail", "6-6-6.flu", "6-6-6.igg", "6-6-6.nut", "6-6-6.usa", "6.emailfake", "60-minuten-mail", "60minutemail", "666-satan", "672643", "675hosting", "67832", "69-ew", "69postix", "6brmwv", "6ceqs4enix.co19", "6hjgjhgkilkj", "6ip", "6mail", "6paq", "6url", "71compete", "75hosting", "7days-printing", "7ddf32e", "7mail", "7mail7", "7pccf", "7rent", "7tags", "7uy35p", "8.fackme", "800sacramento", "806.flu", "80665", "8127ep", "8191", "82c8", "888z5", "88clean", "8chan", "8mail", "900k", "99experts", "99hacks", "99price", "9mail", "9me", "9ox", "9q", "9toplay", "a-b.co", "a-bc", "a.a.fbmail.usa", "a.betr", "a.sach", "a.wxnw", "a0.igg",
  "a0f7ukc", "a1.usa", "a1aemail", "a2.flu", "a41odgz7jh", "a41odgz7jh.com", "a45", "a458a534na4", "a54pd15op", "aa5zy64", "aaaw45e", "aalna", "aamanah", "aaronson", "ab-volvo", "ababmail", "abacuswe", "abakiss", "abcmail", "abcz.info", "abigail69", "abilitywe", "abovewe", "absolutesuccess", "absolutewe", "abundantwe", "abusemail", "abuser", "abyssemail", "abyssmail", "ac20mail", "academiccommunity", "academywe", "acceleratewe", "accentwe", "acceptwe", "acclaimwe", "accordwe", "accreditedwe", "acentri", "acgapp", "achievementwe", "achievewe", "acmeco", "acmilanbangilan", "acornwe", "acrylicwe", "activatewe", "activitywe", "acuitywe", "acumenwe", "adamastore", "adaptivewe", "adaptwe", "adbet", "add3000.pp", "adeptwe", "adesktop", "adipex7z", "adiq", "admiralwe", "adobeccepdm", "adolf-hitler", "adoniswe", "adpugh", "adresseemailtemporaire", "adrianou", "adsd", "adubiz", "advantagewe", "advantimal", "advantimo", "adventurewe", "adventwe", "advisorwe", "advocatewe", "adwaterandstir", "adx-telecom", "ae.pureskn", "aegde", "aegia", "aegiscorp", "aegiswe", "aelo", "aeon", "aeonpsi", "affiliate-nebenjob", "affiliatedwe", "affilikingz", "affinitywe", "affluentwe", "affordablewe", "affricca", "afmail", "afrobacon", "afterhourswe", "ag.us", "ag95", "agedmail", "agendawe",
  "agger", "agilewe", "agistore", "agorawe", "agramas", "agristyleapparel", "agtx", "agustusmp3", "aheadwe", "ahk", "ahmadidik", "aiduisoi3456ta", "airmail", "airmailhub", "airsi", "airwayy", "aistis", "ajaxapp", "aji", "aju.onlysext", "akademiyauspexa", "akapost", "akash9", "akerd", "akgq701", "akhmadi", "akorde", "aktiefmail", "al-qaeda", "albionwe", "alchemywe", "aldeyaa", "aleagustina724", "aleaisyah710", "aleamanda606", "aleanna704", "aleanwisa439", "alebutar-butar369", "aledestrya671", "aleelma686", "aleepapalae", "alefachria854", "alefika98", "alegracia623", "aleherlin351", "alekikhmah967", "alemaureen164", "alemeutia520", "alenina729", "alenoor903", "alenovita373", "aleqodriyah730", "alesapto153", "aleshiami275", "alesulalah854", "aletasya616", "alfa-romeo", "alfamailr", "aliaswe", "alienware13", "aligamel", "alimunjaya", "alisongamel", "alivance", "alivewe", "allaccesswe", "allamericanwe", "allaroundwe", "alldirectbuy", "allegiancewe", "allegrowe", "allen.nom", "allfamus", "allgoodwe", "alliancewe", "allinonewe", "alloutwe", "allowed", "alloywe", "allprowe", "allseasonswe", "allstarwe", "allthegoodnamesaretaken", "allurewe", "almondwe", "alph", "alphaomegawe", "alpinewe", "alsheim.no-ip", "altairwe", "altitudewe", "altuswe", "alumnimp3", "ama-trade", "ama-trans", "amadeuswe", "amail", "amail4", "amav", "amazon-aws",
  "amazon.coms", "ambassadorwe", "amberwe", "ambiancewe", "ambitiouswe", "amelabs", "americanawe", "americasbestwe", "americaswe", "amex-online", "amicuswe", "amigowe", "amilegit", "amiri", "amiriindustries", "amitywe", "amoksystems", "amplewe", "amplifiedwe", "amplifywe", "ampsylike", "an.id", "anakjalanan", "anal.accesscam", "analogwe", "analysiswe", "analyticalwe", "analyticswe", "analyticwe", "anappfor", "anappthat", "andhani", "andreihusanu", "andthen", "animesos", "anit", "ankoninc", "annafathir", "annarahimah", "annazahra", "ano-mail", "anon-mail", "anon.leemail", "anonbox", "anonmail", "anonmails", "anonymail", "anonymbox", "anonymize", "anonymized", "anonymous-email", "anonymousfeedback", "anonymousmail", "anonymousness", "anonymousspeech", "anotherdomaincyka", "ansibleemail", "anthony-junkmail", "anthropologycommunity", "antichef", "antireg", "antispam", "antispam24", "antispammail", "anyalias", "anypen", "anywhere", "ao4ffqty", "aoeuhtns", "apalo", "apfelkorps", "aphlog", "apkmd", "apotekerid", "apoyrwyr", "app-inc-vol", "appc", "appinventor", "appixie", "applynow0", "appnowl", "apps", "aprice", "apssdc", "arakcarpet", "arduino", "area-thinking", "aremania", "ariasexy", "ariaz", "armyspy", "arno", "aron", "arroisijewellery", "art-en-ligne", "artman-conception", "arur01", "arurgitu", "arurimport", "arvato-community",
  "as.onlysext", "asahi", "asana", "aschenbrandt", "asdasd", "asdfasdfmail", "asdfghmail", "asdfmail", "asdhgsad", "asfdasd", "asgaccse-pt", "asgardia-space", "ashik2in", "ashleyandrew", "asiarap.usa", "asik2in", "asiki2in", "asl13", "asls", "asm.snapwet", "asooemail", "asorent", "ass.pp", "asspoo", "assurancespourmoi", "astaghfirulloh", "astonut", "astroempires", "asu", "at", "at0mik", "ateng", "athens5", "atvclub.msk", "audi-r8", "augmentationtechnology", "auoi53la", "aus.schwarzmail", "ausgefallen", "auti", "autorobotica", "autotwollow", "aver", "averdov", "avia-tonic", "avio", "avioaero", "avls", "aw.kikwet", "awatum", "awiki", "awrp3laot", "aws910", "ax80mail", "axeprim", "axiz", "axon7zte", "axsup", "ay33rs.flu", "azazazatashkent", "azcomputerworks", "azjuggalos", "azmeil", "azote", "b.reed", "b.royal-syrup", "b0.nut", "b1of96u", "b2cmail", "b2email", "b5safaria", "b9x45v1m", "b9x45v1m.com", "baban", "babau", "babirousa", "backalleybowling", "backflip", "badamm", "badgerland", "badhus", "badoo", "badoop", "badpotato", "bakar", "balanc3r", "ballsofsteel", "bandai.nom", "bangilan", "banhbeovodich", "banit", "banjarworo", "banjarworocity", "barclays-plc", "bareck", "bareed", "barryogorman", "barrypov", "barryspov", "bartdevos",
  "bartoparcadecabinet", "basketball2in", "basscode", "basssi", "bastore", "batpeer", "bauimail", "bauwerke-online", "baxomale.ht", "bazaaboom", "bbbbyyzz", "bbhost", "bbmail", "bcast", "bcb", "bccto", "bcdmail", "bdmuzic", "bearsarefuzzy", "becausethenight", "beck-it", "beddly", "beefmilk", "beerolympics", "begoz", "bei", "bel", "belamail", "belastingdienst", "belljonestax", "benipaula", "beo", "berlusconi", "best-day", "bestchoiceusedcar", "bestday", "bestfuture", "bestlucky", "bestofprice", "bestoption25", "bestvpn", "bestwishes", "beta.tyrex", "betaprice", "beteajah", "betemail", "betr", "beupmore", "bfo", "bgi-sfr-i", "bgisfri", "bgtmail", "bgx", "bho", "bidourlnks", "big1", "bigcrop", "bigprofessor", "bigstring", "bigwhoop.co", "bigwiki", "bij", "bin.8191", "binka", "binkmail", "binnary", "bio-muesli", "biometicsliquidvitamins", "bione", "birbakmobilya", "birdsfly", "biscutt", "bitwerke", "bitymails", "biz", "bizimalem-support", "bki7rt6yufyiguio.ze", "bko", "blackhole.djurby", "blackmarket", "bladesmail", "blip", "bloatbox", "blogmyway", "blogos", "blogspam", "bloq", "bloxter.cu", "bluebottle", "bluedumpling", "bluewerks", "blutig", "bmw-i8", "bmw-mini", "bmw-rollsroyce", "bmw-x5", "bmw-x6", "bmw-z4", "boatmail", "bobmail",
  "bobmurchison", "bocil", "bodhi.lawlita", "bofthew", "bogotadc", "boimail", "bojogalax", "bondrewd", "bongobongo", "bonobo", "bookthemmore", "booktoplady", "bootybay", "bopunkten", "borged", "borgish", "boss", "bossmail", "bot", "botz", "boun", "bouncr", "box.yadavnaresh.com", "boxformail", "boximail", "boxmail", "boxtemp.com", "bqm2dyl", "brainonfire", "brandallday", "brasx", "breadtimes", "breakthru", "brefmail", "brennendesreich", "briggsmarcus", "bring-luck", "bringluck", "britishintelligence.co", "broadbandninja", "browniesgoreng", "brownieslumer", "bsnow", "bspamfree", "bspooky", "bst-72", "bt3019k", "btb-notes", "btc", "btcmail", "btizet", "buchhandlung24", "budgjhdh73ctr", "buffemail", "bugmenever", "bugmenot", "bulrushpress", "bum", "bumpymail", "bunchofidiots", "bund", "bundes-li", "bungabunga", "bunsenhoneydew", "burgercentral", "burner-email", "burnmail", "burnthespam", "burstmail", "businessbackend", "businesscredit", "businesssuccessislifesuccess", "buspad", "buxap", "buy003", "buydfcat9893lk", "buygapfashion", "buymoreplays", "buyordie", "buyprice", "buyusedlibrarybooks", "bwa33", "by8006l", "byebyemail", "byespm", "byom", "c-mail", "c.andreihusanu", "c.hcac", "c.kadag", "c.nut.emailfake.nut", "c.theplug", "c.wlist", "c0rtana", "c1oramn", "c2", "c3email", "c4ster", "c4utar", "c51vsgq",
  "c6h12o6", "c7fk799", "cachedot", "cadillac-ats", "cafecar", "cahkerjo", "cahsintru", "cakk", "californiafitnessdeals", "cam4you", "campano", "camping-grill", "candymail", "cane", "canyouhearmenow", "car101", "carbtc", "card.zp", "carins", "carrnelpartners", "cars2", "cartelera", "caseedu", "caspianfan", "casualdx", "catch.everton", "cavi", "cazzo", "cbair", "cbes", "cbgh.ddns", "cc", "ccmail", "cd.mintemail", "cd2in", "cdcmail", "cdnqa", "cdpa", "ce.mintemail", "cebong", "ceed", "cek", "cekajahhs", "ceklaww", "cellphoneparts", "cellurl", "cem", "centermail", "central-servers", "centrallosana", "cetpass", "ceweknakal", "cfo2go", "cghdgh4e56fg", "ch", "chacuo", "chammy", "changingemail", "cheap3ddigitalcameras", "cheaphorde", "cheaphub", "cheatmail", "chechnya.conf", "checknew", "chef.asana", "chewiemail", "chibakenma", "chickenkiller", "chielo", "childsavetrust", "chilelinks", "chilkat", "chinatov", "chipekii", "chithinh", "chivasso", "chocklet", "choco", "chogmail", "choicemail1", "chokiwnl", "chong-mail", "choqr6r4", "chris.burgercentral", "christopherfretz", "chumpstakingdumps", "cid", "cigar-auctions", "cilemail", "civilizationdesign", "civvic", "civx", "ckaazaza", "ckiso", "cko", "cl-cl", "cl", "cl0ne", "clandest", "clashatclintonemail",
  "clay", "clean", "clearwatermail", "clendere", "clickanerd", "clickdeal", "clinicatbf", "clintonemailhearing", "clipmail", "clixser", "cloud99", "cloudns", "cloudstreaming", "clrmail", "cls-audio", "clubfier", "clublife", "clue-1", "cmail", "cmc88", "cnamed", "cnew", "cnmsg", "cnn.coms", "cnsds", "co", "cobarekyo1", "cobete", "cobin2hood", "cock", "cocodani", "cocovpn", "codeandscotch", "codivide", "codupmyspace", "codyting", "coepoe", "coepoebete", "coepoekorea", "cognitiveways", "coieo", "colafanta", "coldemail", "coldmail", "colorweb", "com", "combustore", "come-on-day", "comeonday", "comilzilla", "comm.craigslist", "communitybuildingworks", "compareshippingrates", "completegolfswing", "coms", "comsafe-mail", "comwest", "concealed", "conf", "confidential", "config", "consumerriot", "contactout1000", "contbay", "contentwanted", "contractor", "contrasto.cu", "cookiecooker", "cool-your", "cool.fr", "coolandwacky", "coolimpool", "coolyour", "copastore", "coreclip", "correo.blogos", "cortex.kicks-ass", "cosmorph", "courriel.fr", "courrieltemporaire", "covfefe-mail", "cowokbete", "coxbete", "coxbete99", "coza", "cpsystems", "cr97mt49", "crankhole", "crankmails", "crap.kakadua", "crapmail", "crastination", "crazespaces", "crazydoll", "crazymailing", "cream", "cross-law", "crossroadsmail", "crotslep", "crowity",
  "crusthost", "crymail2", "cryp", "crypemail", "crypto.tyrex", "csh", "csoftmail", "cszbl", "ctmailing", "ctos", "cts-lk-i", "cu", "cubiclink", "cul0", "cultmovie", "cumallover", "cumangeblog", "curlhph", "curryworld", "cust", "custom12", "customs2g3", "cutout", "cuvox", "cx.de-a", "cyber-innovation", "cyber-phone", "cybersex", "cylab", "czqjii8", "d.megafon.org", "d1yun", "d3p", "d58pb91", "d8u", "da-da-da", "dab", "dacha-24", "dacoolest", "dadd.kikwet", "daemsteam", "daibond", "daimlerag", "daintly", "dait", "damai", "damanik", "dammexe", "damnthespam", "dancemanual", "danceml", "dandikmail", "darkharvestfilms", "darknode", "daryxfox", "dasdasdascyka", "dash-pads", "dashoffer", "dataarca", "datarca", "datazo", "datum2", "davidkoh", "davidlcreative", "day-one", "dayone", "dayrep", "dbo", "dbunker", "dcemail", "ddcrew", "ddmail", "ddnsfree", "ddosed", "de-a", "de-fake.instafly", "de.sytes", "de4ce", "dea.soon", "deadaddress", "deadchildren", "deadfake", "deadspam", "deagot", "dealja", "dealrek", "decoymail", "deekayen", "defomail", "degradedfun", "delayload", "delikkt", "demandfull", "demen", "dena", "dengekibunko", "dennmail", "der-kombi", "der.madhuratri", "derder",
  "derkombi", "derluxuswagen", "desmo", "despam", "despammed", "dettol", "dev-null", "devnullmail", "dextm", "deyom", "dff55.dynu", "dfg6.kozow", "dfgggg", "dfgh", "dfghj", "dharmatel", "dhm", "dialogus", "dianhabis", "diapaulpainting", "dicksinhisan", "dicksinmyan", "didikselowcoffee", "digdown", "digiprice", "digitalesbusiness", "digitalmariachis", "digitalsanctuary", "dildosfromspace", "dimimail", "dingbone", "dinkmail", "dirtysex", "disaq", "disario", "disbox", "discard-email", "discard", "discardmail", "discordmail", "discos4", "discoverwatch", "discreetfuck", "disign-concept", "disign-revelation", "dislike", "dispo", "dispomail", "disposable-email", "disposable-mail", "disposable", "disposable.dhc-app", "disposableaddress", "disposableemail", "disposableemailaddresses", "disposableemailaddresses.emailmiser", "disposableinbox", "disposablemail", "disposablemails", "dispose", "disposeamail", "disposemail", "dispostable", "divad", "divermail", "divismail", "diwaq", "dko", "dlemail", "dm.w3internet.co", "dm.w3internet.co.ukexample", "dma.in-ulm", "dmail.kyty", "dmail.unrivaledtechnologies", "dmarc", "dmc-12", "dndent", "dnsdeer", "dnses", "doanart", "dob", "docmail", "docs.coms", "doctordieu", "dodgeit", "dodgemail", "dodgit", "dodsi", "doiea", "dolnaa", "dolphinnet", "domajabro", "domforfb1", "domforfb18", "domforfb19", "domforfb2", "domforfb23", "domforfb27", "domforfb29", "domforfb3",
  "domforfb4", "domforfb5", "domforfb6", "domforfb7", "domforfb8", "domforfb9", "domozmail", "donemail", "dontreg", "dontsendmespam", "dooboop", "doquier", "dot-ml", "dotman", "dotmsg", "dotslashrage", "douchelounge", "doughmaine", "doxcity", "doy", "dozvon-spb", "dp76", "dqkerui", "dqnwara", "dr69", "dragons-spirit", "drama", "drdrb", "dred", "drevo", "drid1gs", "drivecompanies", "drivetagdev", "droolingfanboy", "drop.ekholm", "dropcake", "droplar", "droplister", "dropmail", "drynic", "dsiay", "dsleeping09", "dspwebservices", "dt", "duam", "duck2", "dudmail", "duk33", "dukedish", "dump-email", "dumpandjunk", "dumpmail", "dumpyemail", "durandinterstellar", "duskmail", "dusnedesigns", "dvdxpress", "dw.now", "dwango", "dweezlemail.crabdance", "dwse.edu", "dx.abuser", "dx.allowed", "dx.awiki", "dx.ez", "dx.sly", "dyceroprojects", "dynu", "dz-geek", "dz17", "dz57taerst4574", "e-mail", "e-mailbox", "e-postkasten", "e.4pet", "e.amav", "e.arno", "e.benlotus", "e.blogspam", "e.discard-email", "e.l5", "e.milavitsaromania", "e.nodie", "e.shapoo", "e.wupics", "e0yk-mail", "e3z", "e4ward", "e7n06wz", "earth.doesntexist", "earthworksyar", "eastwan", "easy-trash-mail", "easymail", "easynetwork", "easytrashmail", "eatme69", "eatmea2z", "eatrnet", "eay",
  "eb609s25w", "ebano.campano", "ebeschlussbuch", "eboise", "ebs.com", "ec97", "ecallheandi", "echt-mail", "echtzeit", "eco.ilmale", "ecocap", "ecolo-online", "edgex", "edifice", "edinburgh-airporthotels", "edrishn", "edv", "ee1", "ee2", "eeemail", "eelmail", "efo", "efxs", "eho", "einfach", "einmalmail", "einrot", "eins-zwei", "eintagsmail", "ekii", "ekiiajah", "ekiibete", "ekiibeteaja", "ekiibetekorea", "ekiikorea99", "ekiilinkinpark", "elearningjournal", "electro", "elitevipatlantamodels", "ely", "email-fake", "email-jetable", "email-sms", "email-temp", "email.cbes", "email", "email.wassusf", "email60", "emailage", "emaildienst", "emailfake", "emailfake.nut", "emailfake.usa", "emailfreedom", "emailgo", "emailhearing", "emailias", "emailigo", "emailinfive", "emailisvalid", "emaillime", "emailll", "emailmenow", "emailmiser", "emailo", "emailofnd", "emailondeck", "emailproxsy", "emailr", "emailresort", "emails", "emailsecurer", "emailsensei", "emailsingularity", "emailspam", "emailsy", "emailtea", "emailtech", "emailtemporanea", "emailtemporar", "emailtemporario.com", "emailthe", "emailtmp", "emailto", "emailure", "emailwarden", "emailx.at", "emailxfer", "emailz", "emeil", "emeraldwebmail", "emeyle", "emil", "emirmail", "emkei", "eml.pp", "emlhub", "emlpro", "emltmp", "emoreno",
  "empireanime", "empiremail", "emy", "emz", "endrix", "ennemail", "enterto", "entregandobiblia.com", "enu", "envy17", "eny", "eonmech", "epb", "ephemail", "ephemeral", "epot", "eqeqeqeqe", "eqiluxspam", "equiemail", "eramis", "erasedebt", "erasf", "ericjohnson", "ero-tube", "esc", "escapehatchapp", "ese", "esemay", "esgeneri", "esmuse", "esprity", "esseriod", "est.une.victime", "estate-invest", "esy", "etgdev", "eth2btc", "ether123", "ethereal", "ethereum1", "ethersports", "etlgr", "etranquil", "etzdnetx", "euaqa", "eur-sec1", "eur0", "euromail", "evanfox", "everytg", "evilbruce", "evliyaogluotel", "evopo", "evyush", "ewa", "ewer", "eww", "example", "exi", "exitstageleft", "explodemail", "express.net", "extraaaa", "extraaaa2", "extraam", "extremail", "eyepaste", "ez", "ezfill", "ezlo", "ezprice", "ezstest", "f.moza", "f4k", "f5", "facebook-email", "facebookmail", "fackme", "fadingemail", "fag", "failbone", "faithkills", "fake-box", "fake-email.pp", "fake-mail", "fake.i-3gk", "fakedemail", "fakeinbox", "fakeinformation", "fakemail", "fakemail.intimsex", "fakemailgenerator", "fakemailz", "famail", "familytoday", "fammix", "fangoh", "fannny", "fansworldwide", "fantasymail",
  "farfurmail", "farmerlife", "farmtoday", "farrse.co", "fartwallet", "fassagforpresident", "fast-mail", "fastacura", "fastchevy", "fastchrysler", "fastemails", "fastermail", "fasternet", "fastkawasaki", "fastmailforyou", "fastmazda", "fastmitsubishi", "fastnissan", "fastsubaru", "fastsuzuki", "fasttoyota", "fastyamaha", "fatflap", "fathir", "fax.dix", "faze", "fbi.coms", "fbma", "fbmail1", "fc66998", "fca-nv", "fddns", "fdfdsfds", "feamail", "fellow-me", "fellowme", "fer-gabon", "fetchnet.co", "fettometern", "fewminor", "fghmail", "fi-pdl", "fiat-chrysler", "fiat500", "fiatgroup", "fica", "ficken", "fictionsite", "fido", "fightallspam", "figjs", "figshot", "fiifke", "filbert4u", "filberts4u", "film-blog", "filzmail", "findu", "fingermouse", "finnahappen", "fir", "fishfortomorrow", "fivemail", "fixmail", "fizmail", "flarmail", "flash-mail", "flashbox.5july", "flashmail", "fleckens", "flemail", "flirtey", "flitafir", "floodbrother", "flowerss", "flowu", "fls4.gleeze", "flu", "flurre", "flurred", "fly-ts", "flyinggeek", "flyspam", "flyxnet", "fmail", "fmailx", "fnzm", "fobsos", "foobarbot", "foodbooto", "footard", "foquita", "forecastertests", "foreskin", "forexjobing", "forgetmail", "fornow", "forprice", "forspam", "forward",
  "four.fackme", "foxja", "foxtrotter", "foy", "fq1my2c", "fr", "fr33mail", "fragolina2", "framemail", "francanet.com", "frapmail", "frappina", "frappina99", "free-email", "freeaccnt", "freealtgen", "freebabysittercam", "freeblackbootytube", "freebullets", "freecat", "freechristianbookstore", "freedom4you", "freedompop", "freefattymovies", "freelance-france", "freeletter", "freemail", "freemail.tweakly", "freemails", "freemeil", "freemommyvids", "freeplumpervideos", "freeprice", "freeschoolgirlvids", "freeshemaledvds", "freesistercam", "freesistervids", "freeteenbums", "freetubearchive", "freezzzm", "fressmind", "freunde", "freundin", "friendlymail.co", "front14", "fsagc", "fsfsdf", "fsociety", "ftp", "ftpinc", "fuckedupload", "fuckingduh", "fuckme69", "fucknloveme", "fuckxxme", "fudgerub", "fuirio", "fujitv", "fulvie", "fun2", "fun2night", "fun64", "funnycodesnippets", "funnymail", "funxmail", "furusato", "furzauflunge", "futuregood", "fuw65d", "fuwamofu", "fux0ringduh", "fw-nietzsche", "fw.moza", "fw2", "fw6m0bd", "fxnxs", "fyii", "g-meil", "g.hmail", "g.ycn", "g00gl3", "g00glechr0me", "g00gledrive", "g05zeg9i", "g14l71lb", "g1xmail", "g212dnk5", "g2xmail", "g3xmail", "g4hdrop", "gaf.oseanografi", "gafy", "gaggle", "galaxy-s9", "galaxy", "gally", "gamail", "game", "gamegregious", "gameme",
  "games4free.flu", "gamgling", "gamno.config", "gapemail", "garage46", "garasikita", "garbagecollector", "garbagemail", "gardenscape", "garizo", "garliclife", "garrymccooey", "gav0", "gawab", "gbcmail", "gbmail", "gcmail", "gdmail", "geaviation", "gedmail", "geekforex", "geew", "geezmail", "gehensiemirnichtaufdensack", "geldwaschmaschine", "gelitik", "genderfuck", "general-electric", "generator", "geomail", "germanmails", "gero", "geronra", "geschent", "get-mail", "get.pp", "get1mail", "get2mail", "get365", "getairmail", "getapet", "geteit", "getfun", "getmails", "getnada", "getnowtoday", "getonemail", "gfcom", "gg-byron", "ggfutsal", "ghea", "ghgluiis", "ghosttexter", "ghtreihfgh", "giacmosuaviet", "giaiphapmuasam", "giantmail", "gibit", "gicua", "gigs.craigslist", "gimesson.pe", "ginzi", "ginzi.co", "ginzy.co", "ginzy", "giooig", "girlmail", "girlsforfun", "girlsindetention", "girlsundertheinfluence", "gishpuppy", "gitumau", "giuras", "giuypaiw8", "giveh2o", "givmail", "giyam", "glassaas", "glassworks", "gleeze", "glitch", "global.idn", "globaltouron", "glubex", "glucosegrin", "gmail.gr", "gmailbete", "gmaildottrick", "gmailssdf", "gmal", "gmatch", "gmeil", "gmial", "gmx1mail", "gmxmail", "gnctr-calgary", "go.irc", "go1", "go2usa", "go2vpn",
  "goat", "godataflow", "godut", "goemailgo", "gofuckporn", "gogreeninc", "gok", "golemico", "golfilla", "golidi", "gomail", "gomail.pgojual", "gooday", "goodjab", "goodluckforu.cn", "goodseller", "goodsmart", "googdad", "google-email", "google-mail", "googledottrick", "goranko", "gorillaswithdirtyarmpits", "goromail", "goround", "gosearchcity", "gothere", "gotimes", "gotmail", "gotti.otherinbox", "govnomail", "gowikibooks", "gowikicampus", "gowikicars", "gowikifilms", "gowikigames", "gowikimusic", "gowikimusic.great-host", "gowikinetwork", "gowikitravel", "gowikitv", "gqlsryi", "grabitfast", "grandmamail", "grandmasmail", "gratislose", "great-host", "gree", "greencoepoe", "greenekiikoreabete", "greenforce", "greenhousemail", "greensloth", "greenst", "greggamel", "gregorsky", "gregorygamel", "greyjack", "grish", "griuc", "grizzlyfruit", "grn", "grodins", "group-llc", "groupe-psa", "grr", "gs-arc", "gsredcross", "gsrv.co", "gsxstring", "gudanglowongan", "guerillamail", "guerillamailblock", "guerrillamail", "guerrillamailblock", "gustore", "gustr", "gwfh", "gwspt71", "gxemail", "gynzi.co", "gynzi", "gynzy", "gzb", "h.mintemail", "h.thc", "h1tler", "h1z8ckvz", "h2-yy.nut", "h8s", "h9js8y6", "habitue", "hacccc", "hacked", "hackersquad", "hackrz", "hackthatbit", "haddo", "hafnia", "hahawrong",
  "haiapoteker", "haitmail", "halofarmasi", "haltospam", "hamusoku", "hangxomcuatoilatotoro", "hanmama.zz", "hantem", "happygoluckyclub", "happykorea", "happykoreas", "happysinner.co", "happyyou", "haqed", "harakirimail", "hargaku", "haribu", "harmonyst", "hartbot", "harvard-ac-uk", "hasanmail", "hasegawa", "hash.pp", "hat-geld", "hate", "hatespam", "hawrong", "haydoo", "hays", "hazelnut4u", "hazelnuts4u", "hazmatshipping", "hcac", "hccmail", "hdfshsh", "hdmoviestore", "hdprice", "headstrong", "healyourself", "heathenhammer", "heathenhero", "hecat", "hellodream", "helloricky", "hellow-man", "hellowman", "hellowperson", "helm", "helmade", "helpinghandtaxcenter", "helpwesearch", "herp", "herpderp", "hewke", "hezemail", "hezll", "hg8n415", "hi2", "hi5", "hi6547mue", "hiddencorner", "hiddentragedy", "hidebox", "hidemail", "hideme", "hidemyass", "hidzz", "highbros", "hillary-email", "hiru-dea", "hitbts", "hitler-adolf", "hitprice", "hix", "hiz", "hjirnbt56g", "hjkcfa3o", "hjkhgh6ghkjfg", "hku.us", "hmail", "hmamail", "hmh", "hntr93vhdv.uy", "ho3twwn", "hoanggiaanh", "hoanglong", "hochsitze", "hoer", "holl", "homal", "honor-8", "hopemail", "hornyalwary", "horsefucker", "horvathurtablahoz", "hostcalls", "hostlaba", "hostmonitor", "hot-mail", "hotakama",
  "hotlunches", "hotmai", "hotmails", "hotmial", "hotpop", "hotprice", "hous.craigslist", "housat", "housemail", "hpc", "hqcatbgr356z", "hrb67", "hs", "hs130", "hsbc.coms", "hstermail", "ht", "hu4ht", "huajiachem", "huck", "hukkmu", "hulapla", "humaility", "hummer-h3", "humn.ws", "hungpackage", "hunrap.usa", "hurramm", "hurrijian", "hush", "hushmail", "huskion", "hvastudiesucces", "hvtechnical", "hvzoi", "hwsye", "i-3gk", "i-booking", "i-taiwan", "i.istii", "i.klipp", "i.ryanb", "i.wawi", "i.xcode", "i201zzf8x", "i2pmail", "i35t0a5", "i4j0j3iz0", "i6.cloudns", "i66g2i2w", "iaoss", "ibm.coms", "ibnuh", "ibsats", "icantbelieveineedtoexplainthisshit", "iccmail", "icemovie", "icetmail", "icfu.mooo", "ichichich", "ichigo", "icraftx", "icx", "id", "ideepmind", "ideer.msk", "ideer", "idigo", "ieatspam", "ieh-mail", "if58", "ige", "igg", "igintang", "iginting", "igiveu", "ignoremail", "ihateyoualot", "ihaxyour", "ihazspam", "iheartspam", "ikbenspamvrij", "iki", "ikke", "ikkjacket", "iku", "illistnoise", "ilmale", "ilnostrogrossograssomatrimoniomolisano", "ilovemyniggers", "ilovespam", "imails", "imamail1928", "imankul", "imeil", "imgjar", "imgof", "imgv", "imhtcut", "immo-gerance",
  "imovie", "impastore", "imperfectron", "impostore", "imstations", "imul", "inaby", "inapplicable", "inbax", "inbound", "inbox", "inbox2", "inboxalias", "inboxbear", "inboxclean", "inboxdesign", "inboxed", "inboxhub", "inboxproxy", "inboxstore", "inclusiveprogress", "incognitomail", "incq", "ind", "indeedlebeans", "indeedtime", "india2in", "indieclad", "indirect", "indomaed", "indomina", "indonesianherbalmedicine", "indoserver", "indosukses", "ineec", "infest", "info-radio", "infocom.zp", "inggo", "inmynetwork", "inoutmail", "inpowiki", "insanumingeniumhomebrew", "insorg-mail", "instafun", "instant-mail", "instantblingmail", "instantemailaddress", "instantlyemail", "instantmail", "instantmailaddress", "instaprice", "intel.coms", "internetoftags", "interserver", "interstats", "intersteller", "inunglove", "investore", "ioemail", "ioio", "iozak", "ip4.pp", "ip6", "ip6.pp", "ipdeer", "ipemail", "iphonemail", "ipoo", "ippandansei", "ipsur", "ipswell", "iqemail", "irabops", "irc", "ircbox", "irish2me", "irishspringrealty", "iroid", "ironiebehindert", "irr", "irssi", "is", "isdaq", "ise4mqle13.o-r", "islam.igg", "islamm", "isosq", "ispuntheweb", "ispyco", "istakalisa", "istii", "istlecker", "istmail", "isukrainestillacountry", "it2-mail", "it7", "itmtx", "its0k", "itsme.edu",
  "itunesgiftcodegenerator", "iuemail", "iwanbanjarworo", "iwancorp", "iwankopi", "iwantumake", "iwi", "ixx", "j-keats", "j-p", "j.rvb", "j3rqt89ez", "j8-freemail", "jacckpot", "jacquelx", "jafps", "jaguar-landrover", "jaguar-xj", "jajxz", "jamit.com", "jancokancene", "janproz", "javmail", "jcdmail", "jcpclothing", "jdmadventures", "jdtfdf55ghd", "jdz", "je-recycle", "jeep-official", "jellow", "jellyrolls", "jembut142", "jeramywebb", "jerapah993r", "jet-renovation", "jetable", "jetable.fr", "jetable.pp", "jetableemail", "jetableemails", "jfgfgfgdfdder545yy", "jfiee", "jiancok", "jiancokowe", "jil", "jklasdf", "jmail", "jnxjn", "job.craigslist", "jobbikszimpatizans", "jobposts", "jobs-to-be-done", "joelpet", "joetestalot", "john-doe", "johnpo", "jokenaka", "jonrepoza", "jopho", "jorja344cc", "josadelia100", "josalita95", "josalyani102", "josamadea480", "josamanda777", "josangel381", "josasjari494", "josdita632", "josefadventures", "joseihorumon", "josfitrawati410", "josfrisca409", "josgishella681", "joshendriyawati219", "josivangkia341", "josjihaan541", "josnarendra746", "josnurul491", "josprayugo291", "josresa306", "josrustam128", "josse", "josyahya751", "jourrapide", "jp-morgan", "jp.ftp", "jp.hopto", "jpco", "jralalk263", "jredm", "jsonp", "jsrsolutions", "jswfdb48z", "jto", "jumaelda4846", "jumanindya8240", "jumaprilia4191", "jumbunga3502", "jumgita6884",
  "jumlatifani8910", "jummario7296", "jummayang1472", "jumnia4726", "jumnoor4036", "jumnugroho6243", "jumonji", "jumossi51", "jumrestia9994", "jumreynard5211", "jumreza258", "jumveronica8959", "jungkamushukum", "junk.beats", "junk", "junk1e", "junkmail", "jupimail", "just4spam", "justbegood", "justemail", "justnowmail", "justonemail", "justshoes", "jv6hgh1", "jwk4227ufn", "jwork", "jyliananderik", "k.fido", "k3663a40w", "k4ds", "kadag", "kademen", "kadokawa", "kaguya", "kah", "kaijenwan", "kakadua", "kalapi", "kampoeng3d", "kamsg", "kanciang", "kanker", "kaovo", "kappala", "karatraman", "kariplan", "karitas.com", "kartvelo", "kasmail", "kaspop", "katcang", "katztube", "kazelink", "kazper", "kchkch", "kcrw", "kdfgedrdf57mmj", "keeplucky", "keepmymail", "kehangatan", "kein", "keinhirn", "keinpardon", "keipino", "kekecog", "kekita", "keluruk", "kemptvillebaseball", "kemska", "kennedy808", "ketiksms", "kevintrankt", "khalifahallah", "khoabung", "khongsocho", "kiani", "kickmark", "kickmarx", "kiham", "killmail", "kimsdisk", "kingsq", "kiois", "kir.ch", "kismail", "kisstwink", "kitnastar", "kitten-mittons", "klammlose", "klassmaster", "klick-tipp", "klipp", "klipschx12", "kloap", "kludgemush", "klzlk", "kmail.mooo", "kmhow", "knol-power",
  "knolselder", "kodaka", "kodemail", "koiqe", "kommunity", "kon42", "konno", "kook", "kopagas", "kopaka", "kopiacehgayo15701806", "kopibajawapunya15711640", "kopikapalapi11821901", "kopipahit", "kopqi", "koreamail", "koreautara", "kormail", "korutbete", "kosmetik-obatkuat", "kostenlosemailadresse", "koszmail", "kotsu01", "koweancenjancok", "koyocah", "kozow", "krsw.sonshi", "krsw", "krypton", "ksiskdiwey", "ksmtrck", "ksmtrck.rf", "kuai909", "kuaijenwan", "kuatcak", "kuatmail", "kucingarong", "kuemail", "kuhrap", "kuikytut", "kuingin", "kuiqa", "kulturbetrieb", "kumail8", "kurzepost", "kusam", "kusrc", "kwalidd", "kwift", "kwilco", "kyal", "kyois", "l-c-a", "l.safdv", "l0.l0l0", "l0l.l1l", "l2n5h8c7rh", "l33r", "l5", "l7b2l47k", "l8oaypr", "labetteraverouge", "labo", "lacedmail", "lacercadecandi", "lackmail", "lacto", "ladymacbeth", "lags", "lagushare", "laika999", "laikacyber", "lain", "lajoska.pe", "lakelivingstonrealestate", "lal", "lancego", "lancia", "landmail", "laoeq", "laoho", "last-chance", "lastmail", "latemail", "lavabit", "lawlita", "lawlz", "lawson", "lazyinbox", "lbe", "ldop", "ldtp", "ledoktre", "lee", "leeching", "leemail", "legalrc", "lehman", "lei", "lellno",
  "lemper", "lenlusiana5967", "lenmawarni5581", "lennurfitria2852", "lenovog4", "lenprayoga2653", "lenputrima5494", "leonelahmad", "lesbugs", "letmeinonthis", "letmymail", "letsmail9", "letthemeatspam", "levy", "lexisense", "lez", "lgxscreen", "lhsdv", "liamcyrus", "libox", "lifebyfood", "lifetimefriends", "lifetotech", "ligsb", "likesyouback", "lillemap", "lilo", "lilylee", "limahfjdhn89nb", "lindenbaumjapan", "linguistic", "link2mail", "linkedintuts2016", "linux.7m", "linuxmail", "linuxpl", "liquidmail", "lirikkuy", "litedrop", "liveradio", "liveskiff", "livingsalty", "lixo.loxot", "lkgn", "lkim1wlvpl", "lko", "llogin", "lmcudh4h", "loadby", "loan101", "loanins", "loaoa", "localserv.no-ip", "locanto1", "locantofuck", "locantospot", "locantowsite", "locateme10", "locomodev", "logaelda603", "loganisha253", "logardha605", "logartika465", "logatarita892", "logatarita947", "logavrilla544", "logdewi370", "logdufay341", "logefrinda237", "logertasari851", "logesra202", "logeva564", "logfauziyah838", "logfika450", "logfitriani914", "logfrisaha808", "loghermawaty297", "loghning469", "loghusnah2", "logike708", "login-email", "logismi227", "logmardhiyah828", "logmaureen141", "logmoerdiati40", "lognadiya556", "lognoor487", "logoktafiyanti477", "logpabrela551", "logrialdhie62", "logrialdhie707", "logrozi350", "logsharifa965", "logsinuka803", "logstefanny934", "logsutanti589", "logsyarifah77", "logtanuwijaya670", "logtheresia637", "logtiara884",
  "logular", "logutomo880", "logvirgina229", "logw735", "logwan245", "logwibisono870", "logwulan9", "logyanti412", "loh.pp", "loin", "lol.ovpn", "lolfreak", "lolitka", "lolito", "lolllipop", "lolmail", "lom", "london2", "longio", "lonthe", "lookugly", "lopeure", "lopl.co", "lordsofts", "lortemail", "losemymail", "lostpositive", "lovebitco", "lovefall", "lovemeet", "lovemeleaveme", "lovesea", "loy", "loyalherceghalom", "lpfmgmtltd", "lpo.ddnsfree", "lr7", "lr78", "lroid", "lru", "lsrtsgjsygjs34", "luckboy", "luckjob", "luckymail", "lucyu", "luisgiisjsk", "lukecarriere", "lukemail", "lukop", "luo", "lupabapak", "lusianna", "luv2", "lyfestylecreditsolutions", "m-mail", "m.ddcrew", "m21", "m2r60ff", "m4ilweb", "m8r.davidfuhr", "maaill", "maboard", "mabuklagi", "macaniuo235", "macr2", "macromaid", "macromice", "magamail", "maggotymeat", "magicbox", "mahiidev", "maidlow", "mail-easy", "mail-fake", "mail-filter", "mail-owl", "mail-temp", "mail-temporaire", "mail-tester", "mail.aws910", "mail.backflip", "mail.bccto", "mail.bentrask", "mail.bestoption25", "mail", "mail.fast10s", "mail.fettometern", "mail.hanungofficial", "mail.illistnoise", "mail.mailinator", "mail.mezimages", "mail.mixhd", "mail.mnisjk", "mail.myde", "mail.neynt", "mail.partskyline", "mail.piaa", "mail.stars19", "mail.ticket-please", "mail.unionpay",
  "mail.zp", "mail0", "mail1.drama", "mail1.hacked", "mail1.i-taiwan", "mail1.ismoke", "mail1.kaohsiung", "mail1.kein", "mail114", "mail1999", "mail1a", "mail2.drama", "mail2.info", "mail2.ntuz", "mail2", "mail2.worksmobile", "mail2000", "mail2001", "mail21", "mail22", "mail2nowhere", "mail2rss", "mail2tor", "mail2world", "mail3.drama", "mail333", "mail4-us", "mail4.drama", "mail4trash", "mail4you.usa", "mail5.drama", "mail56", "mail666", "mail707", "mail72", "mailabconline", "mailadadad", "mailapi", "mailback", "mailbidon", "mailbiz", "mailblocks", "mailblog", "mailbox52", "mailbox72", "mailbox80", "mailbox92", "mailbucket", "mailcat", "mailcatch", "mailcdn", "mailchop", "mailcker", "mailcom", "mailde", "maildrop", "maildu", "maildump", "maildx", "maileater", "mailed", "maileimer", "maileme101", "mailexpire", "mailf5", "mailfa", "mailfall", "mailfish", "mailforspam", "mailfree", "mailfreeonline", "mailfs", "mailgov", "mailguard", "mailgutter", "mailhazard", "mailhero", "mailhz", "mailimails.patzleiner", "mailimate", "mailin8r", "mailinatar", "mailinater", "mailinator", "mailinator.co", "mailinator2", "mailinatorzz.mooo", "mailinbox", "mailincubator", "mailismagic", "mailita", "mailjunk", "mailkor", "mailmate", "mailme", "mailme.judis", "mailme24", "mailmetrash", "mailmetrash.comilzilla", "mailmoat",
  "mailmoth", "mailms", "mailna", "mailnator", "mailnesia", "mailnull", "mailonaut", "mailorc", "mailorg", "mailpick", "mailpooch", "mailproxsy", "mailquack", "mailrc", "mailrock", "mailsac", "mailscheap", "mailscrap", "mailseal", "mailshell", "mailsiphon", "mailslapping", "mailslite", "mailspam", "mailspeed", "mailsucker", "mailtemp", "mailtempmha", "mailtemporaire", "mailthunder", "mailtome", "mailtothis", "mailtraps", "mailtrash", "mailtrix", "mailtv", "mailwithyou", "mailz.info", "mailzen", "mailzi", "mailzilla", "mailzilla.orgmbx", "mainerfolg", "majorleaguemail", "makasarpost", "makemenaughty", "makemetheking", "makepleasure", "malahov", "malayalamdtp", "malibucoding", "mall.tko.co", "mallinator", "malove", "mamber", "mandraghen", "manifestgenerator", "mankyrecords", "mansiondev", "manybrain", "mao.igg", "markmurfin", "martin.securehost.com", "martyvole", "masasih", "masonline", "mastahype", "maswae", "matamuasu", "matchpol", "materiali", "mattmason", "max88", "maximalbonus", "maxprice", "mbe", "mbx", "mcache", "mcdonald", "mciek", "md5hashing", "mdhc", "mebelnu", "mechanicalresumes", "mediciine", "medsheet", "meepsheep", "mega.zik", "meinspamschutz", "mejjang", "meltedbrownies", "meltmail", "mephistore", "meprice", "merda", "merry", "mesotheliomasrates", "messagebeamer", "messageden", "messagesafe",
  "messwiththebestdielikethe", "metalrika", "metaprice", "metroset", "mettamarketingsolutions", "metuwar", "mezimages", "mfghrtdf5bgfhj7hh", "mfsa", "mhwolf", "miaferrari", "miam.kd2", "micsocks", "midcoastcustoms", "midcoastsolutions", "midlertidig", "mierdamail", "migmail", "migserver2", "migumail", "mihanmail", "mihep", "mijnhva", "milandwi", "milavitsaromania", "mildin.org", "mindmail", "mindsetup", "minecraftrabbithole", "minex-coin", "ministry-of-silly-walks", "minsmail", "mintconditionin", "mintemail", "miodonski", "mipodon", "miraigames", "mirmirchi", "mirrorrr", "mirrror", "misterpinball", "mitsubishi-asx", "mitsubishi-pajero", "mituvn", "miur", "mixi", "mji", "mjukglass", "mjxfghdfe54bnf", "mko", "mkpfilm", "ml8", "mlo", "mm", "mm5", "mmail.igg", "mmailinater", "mmmmail", "mmoonz", "mn.curppa", "mn.riaki", "mnode", "moakt", "mobi.web", "mobileninja.co", "mobilevpn", "moburl", "mockmyid", "moeri", "mohmal", "momentics", "monachat", "monadi", "moncourrier.fr", "monemail.fr", "moneyboxtvc", "moneypipe", "monmail.fr", "monumentmail", "mooblan", "moonm", "moonwake", "moot", "morahdsl", "moreawesomethanyou", "morecoolstuff", "morefunmart", "moreorcs", "morriesworld", "morsin", "motique", "mountainregionallibrary", "movanfj", "mox.pp", "moza", "mozej", "mp-j", "mp3geulis", "mpaaf", "mr24",
  "mrblacklist", "mrchinh", "mrossi", "mrresourcepacks", "ms9.mailslite", "msa.minsmail", "msgden", "msgos", "msgsafe", "msk", "mskey", "mspeciosa", "msrc", "mswork", "msxd", "mt2009", "mt2014", "mt2015", "mt2016", "mt2017", "mtmdev", "muathegame", "muchomail", "mucincanon", "muehlacker", "muell", "muellpost", "mufux", "mugglenet", "muimail", "mundri", "munoubengoshi", "muq.orangotango", "musclemailbox", "musicmakes", "mustbe.ignorelist", "mustbedestroyed", "musttufa", "mutant", "muttvomit", "muttwalker", "mvrht", "mwarner", "mx0.wwwnew", "mxfuel", "my-email", "my-server-online", "my.efxs", "my.longaid", "my.vondata.com", "my10minutemail", "myalias", "mybitti", "mycard.net", "mycleaninbox", "mycorneroftheinter", "myde", "mydemo", "myecho", "myemailboxy", "myfake", "myfakemail", "myindohome", "myinterserver", "mykickassideas", "mymail-in", "mymailjos", "mymailoasis", "mymailto", "myn4s.ddns", "myneocards", "mynetstore", "mynetwork", "myopang", "mypacks", "mypartyclip", "myphantomemail", "myproximity", "mysafemail", "mysamp", "myspaceinc", "myspacepimpedup", "myspamless", "mystvpn", "mytemp", "mytempemail", "mytempmail", "mythnick", "mytrashmail", "mywarnernet", "myzx", "n.ra3", "n.spamtrap", "n.zavio", "n1nja", "n8", "naaughty", "nabuma", "nacho", "nada",
  "nafko", "nakedtruth", "nameaaa.myddns", "namefake", "namilu", "nanonym", "napalm51", "nash", "nationalgardeningclub", "naturalious", "nawmin", "nbhsssib", "nbox.notif", "nctuiem", "ndemail", "ndfakemail", "ndfbmail", "ndinstamail", "ndmail", "negated", "neibu306", "neibu963", "neko2", "nenengsaja", "neomailbox", "nepnut", "nepwk", "nervmich", "nervtmich", "net", "netmails", "netricity", "netris", "netviewer-france", "networkofemail", "netzidiot", "neverbox", "nevermail", "new-purse", "newbpotato", "newdawnnm", "newideasfornewpeople", "newsmag", "newsusfun", "next", "nextstopvalhalla", "nezdiro", "nezzart", "nfast", "nguyenusedcars", "nh3", "nice-4u", "nicegarden", "nicewoodenbaskets", "nickbizimisimiz", "nicknassar", "nie-podam", "niepodam", "nigge", "nike.coms", "nincsmail", "niwl", "njc65c15z", "njelarubangilan", "njelarucity", "nkhfmnt", "nko", "nktltpoeroe", "nl.szucsati", "nm7", "nmail", "nnh", "nnot", "no-spam", "no-spammers", "no-ux", "no-vax", "noblepioneer", "nobugmail", "nobulk", "nobuma", "noclickemail", "nodezine", "nodie", "nodnor", "nogmailspam", "noicd", "nokiamail", "nolemail", "nom", "nomail", "nomail.nodns", "nomail.xl", "nomail2me", "nomailthankyou", "nomeucu", "nomorespamemails", "nonexisted", "nonspam", "nonspammer",
  "nonze", "noref", "norih", "norseforce", "northemquest", "nosh", "nospam.barbees", "nospam.thurstons", "nospam.wins.com", "nospam.ze", "nospam4", "nospamfor", "nospammail", "nospamme", "nospamthanks", "nostrajewellery", "nothingtoseehere", "notif", "notmail", "notmailinator", "notrnailinator", "notsharingmy", "now", "noway", "nowemail", "nowhere", "nowmymail", "nownaw", "npv", "nqav95zj0p.kro", "nsaking", "ntlhelp", "ntt.gotdns", "ntub", "nubescontrol", "nullbox", "nunung", "nunungcantik", "nunungnakal", "nuo.co", "nuo", "nuprice", "nurdea", "nurfuerspam", "nus.edu", "nut", "nutpa", "nuts2trade", "nwldx", "nwytg", "ny7", "nypato", "o.cfo2go", "o.idigo", "o.muti", "o.oai", "o.opendns", "o.spamtrap", "o060bgr3qg", "o22", "o2stk", "o7i", "oai", "oalsp", "obfusko", "objectmail", "obo", "obobbo", "oboymail", "obxpestcontrol", "oceancares", "odaymail", "odnorazovoe", "oe1f42q", "oepia", "oerpub", "office.ms365", "offshore-proxies", "ohaaa", "ohdomain", "ohi", "ohioticketpayments", "oing", "oiqas", "ojosambat", "ok-body", "okbody", "okclprojects", "okrent", "okzk", "olypmall", "omail", "omeaaa124.ddns", "omi4", "omnievents", "omzae", "one-time", "one", "one2mail", "onebiginbox",
  "onelegalplan", "onemoremail", "oneoffemail", "oneoffmail", "onewaymail", "onlatedotcom", "online", "onlineidea", "onmail", "onprice", "onqin", "ontyne", "oolus", "oopi", "oou", "opayq", "opendns", "openmailbox", "openmindedzone", "opentrash", "opmmedia", "opowlitowe53", "opp24", "orange-bonplan", "orangotango", "ordinaryamerican", "oreidresume", "org", "orgmbx", "oriete", "oroki", "oshietechan", "otherinbox.codupmyspace", "otherinbox", "otonmail", "ourklips", "ourpreviewdomain", "outlawspam", "outlook.com.hotpusssy69", "outlookkk", "outlookpro", "outmail", "ov3u841", "ovimail", "ovlov", "ovpn", "ovvee", "owa", "oweiidfjjif", "owlpic", "ownsyou", "oxfarm1", "oxopoha", "oyu", "ozozwd2p", "ozumz", "ozyl", "p-gdl", "p.9q", "p.k4ds", "p33", "p71ce1m", "pa9e", "pagamenti", "pakadebu", "paller", "palpialula", "pals-pay54", "pamposhtrophy", "panama-real-estate", "pancakemail", "pandostore", "panelpros", "papermakers", "paplease", "paramail", "parkcrestlakewood", "parlimentpetitioner", "partskyline", "party4you", "passionwear", "password.colafanta", "password.nafko", "passwort.schwarzmail", "pastebitch", "pasukanganas", "paulfucksallthebitches", "paulkippes", "pavilionx2", "pay-pal48996", "pay-pal55424", "pay-pal63", "pay-pal8585", "pay-pal8978746", "pay-pals", "pay-pals54647", "pay-pals5467", "payperex2", "pb-shelley", "pc1520",
  "pcmylife", "pcusers.otherinbox", "pe", "peapz", "pecdo", "pedimed-szczecin", "pejovideomaker", "pelor", "pencalc", "penguincreationdate", "penis", "penisgoes", "penoto", "peopledrivecompanies", "pepbot", "peppe.usa", "pepsi.coms", "perasut", "perfect-u", "perfectu", "pers.craigslist", "persebaya1981", "persebaya1999", "personal-email", "peterdethier", "petertijj", "petrolgames", "petrzilka", "pfui", "pgioa4ta46", "pharmasiana", "phd-com", "phecrex", "phonearea", "photo-impact", "photomark", "phpbb.uu", "phuongpt9", "phus8kajuspa.cu", "pi", "pidmail", "pig.pp", "pii", "pika.pc486", "piki", "pilpres2018", "pimpedupmyspace", "pinehill-seattle", "pingir", "pippop", "pippopmig33", "pippopmigme", "pisls", "pjjkp", "plexolan", "plhk", "ploae", "plw", "po.bot", "poalmail", "podam", "poh.pp", "pojok", "pokeett", "pokemail", "pokiemobile", "polacy-dungannon", "polarkingxx", "polimi", "politikerclub", "poliusraas", "polres-aeknabara", "polyfaust", "polymnestore", "pooae", "poofy", "pookmail", "poopiebutt", "pop3", "popconn", "popesodomy", "popgx", "popmail", "popmailserv", "popsok", "porco", "porsh", "porta.loyalherceghalom", "posdz", "posta", "postacin", "postalmail", "postonline", "posurl", "poutineyourface", "powered", "powerml", "powlearn", "poy", "pp",
  "pp98", "ppetw", "ppymail", "pravorobotov", "prayersa3", "predatorrat", "premium-mail", "premiumperson", "preseven", "prestore", "pricebit", "priceblog", "priceio", "pricenew", "pricenow", "priceonline", "pricepage", "priceworld", "pride.nafko", "primabananen", "prince-khan", "prismlasers", "privacy", "privatdemail", "privy-mail", "privymail", "pro-tag", "procrackers", "project-xhabbo", "projectcl", "proprice", "proprietativalcea", "propscore", "protempmail", "protestore", "proxsei", "proxymail", "proxyparking", "prs7", "prtnx", "prtz", "psh", "psles", "psoxs", "psychedelicwarrior", "pterodactyl", "publi.innovatio", "pubmail886", "pubs", "puglieisi", "puji", "pulpmail", "pulwarm", "pumps-fashion", "punggur", "punkass", "purcell", "purelogistics", "purplemail", "put2", "puttanamaiala", "putthisinyourspamdatabase", "pw.islam.igg", "pw.loyalherceghalom", "pwp", "pwrby", "q314", "q5vm7pi9", "q7t43q92", "q7t43q92.com", "qaetaldkgl64ygdds", "qafatwallet", "qasti", "qbfree", "qbi", "qbmail", "qc", "qcmail.qc", "qibl", "qipmail", "qiq", "qisdo", "qisoa", "qj97r73md7v5", "qlhnu526", "qocya", "qoika", "qopmail", "qpalong", "qq", "qqqwwwil", "qqzymail", "qs.dp76", "qs2k", "qsl", "qt1.ddns", "qtum-ico", "quadrafit", "quaestore", "querydirect",
  "questore", "queuem", "quickinbox", "quickmail", "quickreport", "quid4pro", "quintania", "ququb", "qvap", "qvy", "qwertymail", "qwickmail", "qwqrwsf", "r-mail", "r.yasser", "r0.igg", "r31s4fo", "r4nd0m", "r8r4p0cb", "ra3", "rabin", "rabiot", "rabuberkah", "radecoratingltd", "raetp9", "raiasu", "raikas77", "raimu", "raimucok", "raimuwedos", "rainmail", "rainwaterstudios", "rajarajut", "rajeshcon", "raketenmann", "rampas", "rampasboya", "rancidhome", "randomail", "rao", "rapenakyodilakoni", "raqid", "rarame", "raspberrypi123.ddns", "rav-4", "rav4", "rawhidefc", "rawmails", "rax", "raxtest", "razemail", "rbb", "rblx", "rcasd", "rcpt", "rcs7", "rdklcrv", "re-gister", "reality-concept", "reallymymail", "realtyalerts", "receiveee", "recipeforfailure", "recode", "recognised", "reconmail", "recruitaware", "recursor", "recyclemail", "redchan", "reddithub", "redfeathercrow", "redmail", "redpeanut", "redpen", "reftoken", "refurhost", "reg19", "regbypass", "regbypass.comsafe-mail", "regspaces", "rejectmail", "rejo", "reliable-mail", "remail", "remarkable", "remote", "renault-sa", "renaulttrucks", "renraku", "repolusi", "reptilegenetics", "rerajut", "res.craigslist", "reservelp", "resgedvgfed", "resistore", "resolution4print", "rethmail", "retkesbusz.nut",
  "revolvingdoorhoax", "rfc822", "rgb9000", "rgphotos", "rhombushorizons", "rhyta", "riamof", "rich-money", "richfinances", "richfunds", "richmoney", "richonedai", "richsmart", "ricret", "ricrk", "riddermark", "risingsuntouch", "riski", "rklips", "rko", "rkomo", "rma", "rmqkr", "rnailinator", "ro", "robertspcrepair", "robo3", "robot2", "rockkes", "rohingga", "rollindo", "ronnierage", "rooftest", "rootfest", "rotaniliam", "row", "rowe-solutions", "royal", "royaldoodles", "roys", "rppkn", "rq1", "rq6668f", "rr-0.cu", "rr-1.cu", "rr-2.cu", "rr-3.cu", "rr-group", "rrwbltw", "rs311e8", "rtotlmail", "rtrtr", "rtskiya", "rudymail", "ruffrey", "ruggedinbox", "rumgel", "runi", "ruru", "rustydoor", "ruu", "rvb", "rx.dred", "rx.qc", "rxtx", "ryanb", "s-mail", "s-s.flu", "s-s.igg", "s-s.nut", "s-s.usa", "s.bloq", "s.bungabunga", "s.dextm", "s.proprietativalcea", "s.vdig", "s00.orangotango", "s0ny", "s33db0x", "s51zdw001", "s8sigmao", "saab9-3", "saab9-4x", "saab9-5", "saab9-7x", "saab900", "saabgroup", "sabrestlouis", "sach", "sackboii", "safaat", "safe-mail", "safermail", "safersignup", "safetymail", "safetypost", "saharanightstempe", "sahrulselow", "salaopm", "sale.craigslist",
  "salmeow", "salonyfryzjerskie", "samsclass", "samsunggalaxys9", "sandelf", "sandre", "sandwhichvideo", "sanfinder", "sanim", "sanstr", "santhia", "sapbox", "sapya", "sasa22.usa", "sast", "satcom", "satisfyme", "satukosong", "sausen", "savelife", "saxfun", "saynotospams", "scatmail", "scay", "scbox.one", "schachrol", "schafmail", "schmeissweg", "schrott-email", "schwarzmail", "scmail", "sd3", "sdf", "sdfghyj", "sdnr", "searzh", "seasideorient", "secmail", "secret-area", "secretemail", "sector2", "secure-fb", "secure-mail", "secured-link", "securehost.com", "securemail", "secureserver.usa", "securesys", "securesystems-corp", "seekapps", "seekjobs4u", "sejaa", "selfdestructingmail", "sellim", "selowcoffee", "selowhellboy", "semangat99", "semut-kecil", "semutkecil", "send-email", "send22u", "sendfree", "sendingspecialflyers", "sendspamhere", "sendto", "senseless-entertainment", "sensualerotics", "senttmail", "sepatusupeng", "seriousalts", "serv.craigslist", "server", "servermaps", "service4", "services391", "sexforswingers", "sexical", "sexxfun69", "sexyalwasmi", "sexyalwax", "sexymail", "sezet", "sfmail", "shahimul", "shalar", "shapoo", "sharedmailbox", "sharklasers", "shhmail", "shhuut", "shieldedmail", "shieldemail", "shiftmail", "shipfromto", "shiphazmat", "shipping-regulations", "shippingterms", "shitaway", "shitmail", "shitposting",
  "shittymail", "shitware", "shmeriously", "shockinmytown.cu", "shonky", "shopbaby", "shopussy", "shorten.tempm", "shortmail", "shotmail", "showme", "showslow", "shrib", "shuffle", "shurs", "shut", "sicamail", "sidamail", "sify", "sign-up", "sikdar", "sikomo", "sikux", "siliwangi", "simpleitsecurity", "simscity", "simsmail", "sin", "sinda", "sinfiltro", "singlespride", "singssungg", "sink.fblay", "sinnlos-mail", "sino", "siteposter", "six-six-six", "sizzlemctwizzle", "sjuaq", "skeefmail", "skrx", "sky-inbox", "sky-mail", "sky-ts", "skydrive", "skymail", "slapsfromlastnight", "slaskpost", "slave-auctions", "slippery", "slipry", "slopsbox", "slothmail", "slowfoodfoothills", "slowslow", "sls", "slsrs", "slu21svky", "slugmail", "slushmail", "slutty", "sly", "smallker", "smap.4nmv", "smapfree24", "smaretboy", "smarttalent", "smashmail", "smellfear", "smellrear", "smellypotato", "smoug", "smsforum", "smtp33", "smtp99", "smuse", "smwg", "snakemail", "snam", "sneakemail", "sneakerbunko", "sneakmail", "snkmail", "snpsex", "so-com", "so-net", "social-mailer", "socialfurry", "sofimail", "sofort-mail", "sofortmail", "softbank", "softpls", "sogetthis", "sohai", "sohu", "soisz", "solar-impact", "solowtech", "solvemail",
  "solventtrap", "sonshi", "soodmail", "soodomail", "soodonims", "soon", "sosmanga", "sp.woot", "spa", "spaereplease", "spam-be-gone", "spam-en", "spam-nicht", "spam.2012-2016", "spam.fassagforpresident", "spam.flu", "spam.igg", "spam", "spam.netpirates", "spam.nut", "spam.org", "spam.pyphus", "spam.trajano", "spam.usa", "spam4", "spamail", "spamarrest", "spamavert", "spambob", "spambog", "spambooger", "spambox", "spambox.irishspringrealty", "spamcannon", "spamcero", "spamcon", "spamcorptastic", "spamcowboy", "spamday", "spamdecoy", "spameater", "spamex", "spamfighter", "spamfree", "spamfree24", "spamgoes", "spamgourmet", "spamherelots", "spamhereplease", "spamhole", "spamify", "spaminator", "spamkill", "spaml", "spamlot", "spammail", "spammedic", "spammehere", "spammotel", "spamobox", "spamoff", "spamsalad", "spamserver", "spamslicer", "spamspot", "spamstack", "spamthis.co", "spamthisplease", "spamtrail", "spamtrap", "spamtroll", "spamwc", "spb", "speed.1s", "speedgaus", "sperma", "spikio", "spoofmail", "sportylife", "spr", "spritzzone", "spybox", "sqoai", "squirtsnap", "squizzy", "sr.ro", "sraka", "sroff", "sry", "ss.undo", "ss00", "ss01", "ss02", "ssgjylc1013", "sso-demo-okta", "ssoia", "sssppua", "ssunz", "st-m", "stanford-edu",
  "stanfordujjain", "starlight-breaker", "startfu", "startkeys", "statdvr", "stathost", "statiix", "statx", "stealthypost", "steambot", "steamprank", "steemail", "stexsy", "stg.malibucoding", "stinkefinger", "stop-my-spam", "stop-my-spam.pp", "stophabbos", "storal", "storant", "storeamnos", "storectic", "storective", "storeillet", "storellin", "storendite", "storenia", "storent", "storeodon", "storeodont", "storeodoxa", "storeortyx", "storeotragus", "storero", "storestean", "storesteia", "storeutics", "storeweed", "storewood", "storist", "storj99", "stpetersandstpauls", "streamfly", "streetwisemail", "stromox", "stuckmail", "studentmail", "students-class1", "studiopolka", "studioro", "stuff.munrohk", "stuffmail", "stumpfwerk", "styliste", "subaru-brz", "subaru-wrx", "subaru-xv", "subpastore", "suburbanthug", "successforu", "successlocation", "suckmyd", "sucknfuck", "sudolife", "sudomail", "sudoverse", "sudoweb", "sudoworld", "suioe", "sumitra", "suntory", "super-auswahl", "supergreatmail", "supermail", "supermailer", "superplatyna", "superrito", "superstachel", "suremail", "surfmail", "surveyrnonkey", "susi", "sutann", "sute", "sutiami", "suzukilab", "svk", "svxr", "sweetpotato", "sweetxxx", "swift10minutemail", "sxylc113", "sylvannet", "symphonyresume", "syosetu", "syujob", "szerz", "sztyweta46", "szucsati", "t.psh",
  "t099", "t24e4p7", "t3t97d1d", "tafmail", "tafoi", "taglead", "tagmymedia", "tagyourself", "tai-asu", "takedowns", "takeshobo", "talkinator", "talkmises", "tanukis", "taosjw", "tapchicuoihoi", "taphear", "tapsitoaktl353t", "tarma", "tarzanmail", "taskforcetech", "tauttjar3r46", "tb-on-line", "tdf-illustration", "te.caseedu", "teamspeak3", "tech69", "techemail", "techgroup", "techmail", "technikue", "teemia", "teerest", "teewars", "tefl", "telecomix", "telekgaring", "telekteles", "telekucing", "teleosaurs", "teleworm", "tellos", "temp-emails", "temp-mail", "temp-mails", "temp.bartdevos", "temp.emeraldwebmail", "temp.headstrong", "temp.mail.y59", "temp.wheezer", "temp1", "temp15qm", "temp2", "tempail", "tempalias", "tempe-mail", "tempekmuta", "tempemail", "tempemail.co", "tempemails", "tempinbox.co", "tempinbox", "tempm", "tempmail", "tempmail.sytes", "tempmail2", "tempmaildemo", "tempmailer", "tempomail", "temporamail", "temporarily", "temporarioemail.com", "temporaryemail", "temporaryforwarding", "temporaryinbox", "temporarymailaddress", "tempr", "tempsky", "tempthe", "tempymail", "tenesu", "terminate", "ternaklele", "tert353ayre6tw", "test", "testoh", "testore", "testudine", "tf7nzhw", "tfwno", "thanksnospam", "thankyou2010", "thatim", "thc", "theaperturelabs", "theaperturescience", "theaviors", "thebearshark", "thebest4ever", "thebestremont",
  "thecloudindex", "thediamants", "thedirhq", "thelightningmail", "thelimestones", "themail.krd", "thembones.com", "themostemail", "thenewsdhhayy", "theone2017", "theopposition", "theothermail", "theplug", "thereddoors", "thescrappermovie", "theslatch", "thespawningpool", "theteastory", "thetrash", "thex", "thietbivanphong", "thinkingus24", "thisisnotmyrealemail", "thismail", "thisurl", "thnikka", "thraml", "thrma", "throam", "thrott", "throwam", "throwawayemail", "throwawayemailaddress", "throwawaymail", "throya", "thuguimomo", "thunkinator", "thxmate", "tiapz", "tic", "ticket-please", "tijdelijkmailadres", "tilien", "timekr", "timgiarevn", "timkassouf", "tinoza", "tinyurl24", "tipsb", "tirreno", "tittbit", "tiv", "tizi", "tkeiyaku", "tkitc", "tkmy88m", "tko", "tlpn", "tm.slsrs", "tm.tosunkaya", "tm2mail", "tmail", "tmailinator", "tmails", "tmo", "tmpeml", "tmpjr", "tmpmail", "tntitans", "toddsbighug", "toi", "toiea", "tokem", "tokenmail", "tokuriders", "tonymanso", "tool.pp", "toomail", "toon", "toothandmail", "top101", "top1mail", "top1post", "top9appz", "topinrock", "toplessbucksbabes", "topmailings", "topmall", "topofertasdehoy", "topranklist", "toprumours", "tormail", "toss", "tosunkaya", "totalvista", "totesmail", "totoan", "toyota-rav-4", "toyota-rav4", "toyota-yaris",
  "tp-qa-mail", "tqoai", "tqosi", "tracciabi", "tradermail", "tralalajos", "tranceversal", "transistore", "trash-amil", "trash-mail", "trash-me", "trash2009", "trash2010", "trash2011", "trash247", "trash4", "trashbox", "trashcanmail", "trashdevil", "trashemail", "trashemails", "trashimail", "trashinbox", "trashmail", "trashmailer", "trashmails", "trashymail", "trasz", "trayna", "trbvm", "trbvn", "trbvo", "trebusinde", "trendingtopic", "trgovinanaveliko", "trialmail", "trickmail", "trillianpro", "trobertqs", "trollproject", "tropicalbass", "trumpmail", "trungtamtoeic", "tryalert", "tryprice", "ts-by-tashkent", "tspzeoypw35", "tsukushiakihito", "tt2dx90", "ttdfytdd", "ttszuo", "tualias", "tubanmentol", "tubruk", "tucumcaritonite", "tug.minecraftrabbithole", "tukudawet", "tukupedia", "turoid", "turual", "tvchd", "tverya", "tweakly", "twelvee", "twinmail", "twitt3r", "twkly", "twocowmail", "twoweirdtricks", "txt7e99", "txtadvertise", "ty.ceed", "ty.squirtsnap", "tyhe", "tyldd", "tz", "u-wills-uc", "u.0u", "u.10x", "u.2sea", "u.900k", "u.civvic", "u.dmarc", "u.labo", "u.qvap", "u1.myftp", "u14269", "u4nzbr5q3", "u6lvty2", "ua3jx7n0w3", "uacro", "uarara5ryura46", "ubismail", "ubm", "ucandobest", "ucansuc", "ucche", "ucupdong", "ucylu", "udns",
  "udoiswell", "uemail99", "ufacturing", "ufgqgrid", "uggsrock", "ugimail", "ugreatejob", "uguuchantele", "uha", "uhhu", "uikd", "uiu", "ujijima1129", "uk-unitedkingdom", "uk", "ukexample", "ukjton", "uko", "umail", "umy", "undo", "unicredit", "unids", "unimark", "unit7lahaina", "unlimit", "unmail", "unpastore", "uny", "uphomail", "upliftnow", "uplipht", "uploadnolimit", "upozowac", "upy", "uralplay", "urbanchickencoop", "ureee", "urfey", "urfunktion", "uroid", "us", "usa-gov", "usa", "usa.isgre", "usachan", "uscaves", "used-product", "usenetmail", "username.e4ward", "ushijima1129", "usiaj", "utiket", "utilities-online", "uu", "uu2", "uuroalaldoadkgk058", "uvy", "uw5t6ds54", "uwillsuc", "uwork4", "ux.dob", "ux.uk", "uyhip", "uyu", "uz6tgwk", "uzrip", "v.0v", "v.jsonp", "v21.me", "vaasfc4", "vaati", "vaffanculo", "valemail", "valhalladev", "vanacken", "vanbil", "vankin", "vay", "vba", "vctel", "vda", "vdig", "vedula", "vektik", "veldmail", "vemomail", "venompen", "veo", "ver0", "vercelli", "verdejo", "vermutlich", "veryday", "veryprice", "veryrealemail", "vesa", "vfemail", "vhglvi6o", "via.tokyo",
  "vickaentb", "victime", "victoriantwins", "vidchart", "viditag", "viewcastmedia", "vihost", "vikingsonly", "vinernet", "vinsmoke", "vip-mail", "vip", "vipepe", "vipmail", "vipsohu", "vipxm", "viralhits", "viralplays", "virgilio", "virgiliomail", "viroleni.cu", "visa-securepay", "visa.coms", "visal007", "visal168", "vistomail", "vistore", "vixletdev", "vkcode", "vmail", "vmailing", "vmani", "vmpanda", "vncoders", "vnedu", "voidbay", "volvo-v40", "volvogroup", "vomoto", "vonbe", "vorga", "votiputox", "voxelcore", "vp.ycare", "vpn", "vpn33", "vprice", "vps30", "vps911", "vpsorg", "vpstraffic", "vrmtr", "vrsim", "vs904a6", "vsimcard", "vssms", "vtxmail", "vubby", "vuiy", "vuzimir", "vvx046q", "vw-audi", "vw-cc", "vw-seat", "vw-skoda", "vyhade3z", "vzlom4ik", "vztc", "w.0w", "w22fe21", "w3internet.co", "w4i3em6r", "w918bsq", "w9f", "w9y9640c", "wakingupesther", "walala", "walkmail", "wallm", "want2lov", "wantplay", "warau-kadoni", "wasd.10mail", "wasd.dropmail", "wasdfgh", "wasteland.rfc822", "watch-harry-potter", "watchever", "watchfull", "watchironman3onlinefreefullmovie", "wawi", "wazabi", "wbml", "we.lovebitco", "we.qq", "wealthymoney", "web-contact", "web-emailbox", "web-ideal", "web-mail.pp",
  "web.discard-email", "web", "web2mailco", "webarnak.fr.eu", "webcontact-france", "webemail", "webhostingdomain", "webide", "webkiff", "webm4il", "webmail.kolmpuu", "webmeetme", "webtrip", "webuser", "wedooos", "wee", "wef", "wefjo.grn", "weg-beschlussbuch", "weg-werf-email", "wegas", "wegwerf-email-addressen", "wegwerf-email-adressen", "wegwerf-email", "wegwerf-emails", "wegwerfadresse", "wegwerfemail", "wegwerfemailadresse", "wegwerfmail", "wegwerpmailadres", "wegwrfmail", "welikecookies", "wem", "wesandrianto241", "wesatikah407", "wesazalia927", "weselvina200", "weseni427", "wesfajria37", "wesfajriah489", "wesgaluh852", "weshasni356", "weshutahaean910", "wesjuliyanto744", "weskusumawardhani993", "wesmubasyiroh167", "wesmuharia897", "wesnadya714", "wesnurullah701", "wesruslian738", "wessastra497", "wesw881", "weswibowo593", "weswidihastuti191", "wesyuliyansih469", "weszwestyningrum767", "wetrainbayarea", "wfgdfhj", "wg0", "wh4f", "whatiaas", "whatifanalytics", "whatpaas", "whatsaas", "whiffles", "whitebot", "whitemail", "wholesaleelec", "whopy", "whtjddn.33mail", "whyspam", "wibblesmith", "wicked-game", "wickmail", "widaryanto", "widget", "wierie", "wiki.8191", "wikidocuslava", "wikilibhub", "wikipedia-inc", "wikipedia-llc", "wikisite", "wil", "wilemail", "willhackforfood", "williamcastillo", "willselfdestruct", "wimsg", "winemaven", "wins.com", "wirawan", "wirawanakhmadi", "wishan", "with-u", "wiz2", "wjhndxn", "wla9c4em", "wlist", "wmail",
  "wn8c38i", "wolfmission", "wolfsmail", "wolfsmails", "wollan", "wolukiyeh88jik", "wongndeso", "wordme", "work4uber", "worldpetcare", "worldsonlineradios", "worldspace", "wormseo", "wow.royalbrandco", "wpeopwfp099", "wpg", "wpmail", "wr.moeri", "wr9v6at7", "wralawfirm", "writeme", "wronghead", "ws", "wt2.orangotango", "wudet", "wuespdj", "wupics", "wuzup", "wuzupmail", "wvl238skmf", "www.bccto", "www.e4ward", "www.gishpuppy", "www.live.co.kr.beo", "www.mailinator", "www.redpeanut", "wwweb", "wwwmail", "wwwnew", "wxnw", "wyvernia", "wzukltd", "x-mail", "x.ip6", "x1x.spb", "x1x22716", "x24", "x4y", "x5a9m8ugq", "x8h8x941l", "xagloo", "xbaby69", "xc05fypuj", "xcode", "xcompress", "xcpy", "xemaps", "xemne", "xents", "xf.sluteen", "xing886.uu", "xinzk1ul", "xjoi", "xl", "xlgaokao", "xloveme", "xmail", "xmaily", "xn--9kq967o", "xn--b-dga", "xn--d-bga", "xnmail.mooo", "xoixa", "xoru", "xost", "xoxox", "xoxy", "xpee", "xperiae5", "xprice", "xrho", "xtrars", "xv9u9m", "xwaretech", "xww", "xx-9", "xxhamsterxx", "xxi2", "xxlocanto", "xxme", "xxolocanto", "xxqx3802", "xy9ce", "xyzfree", "xyzmail", "xzsok", "y.bcb", "y0up0rn", "y59", "ya.yomail",
  "yabai-oppai", "yadavnaresh.com", "yahmail", "yahomail", "yahoodashtrick", "yalild", "yamail", "yandere.cu", "yanet", "yannmail", "yapped", "yaqp", "yaraon", "yasser", "ycare", "ycn", "ye", "yedi", "yellow.hotakama", "yelloww", "yentzscholarship", "yep", "yewma46eta", "yewmail", "ygroupvideoarchive", "yhcaturkl79jk", "yhcaturxc69ol", "yhg", "yj3nas", "ymail", "ynmrealty", "yodx", "yogamaven", "yomail", "yoo", "yood", "yop", "yop.ze", "yopmail.biz", "yopmail", "yopmail.pp", "yordanmail", "yormanwhite", "yoru-dea", "you-spam", "you.e4ward", "youbestone", "youcankeepit", "yougotgoated", "youmail", "youmailr", "youneedmore", "youporn.flu", "youporn.igg", "youporn.usa", "yourdomain", "youremail", "yourewronghereswhy", "yourlms", "yourtube", "youzend", "ypmail.webarnak.fr.eu", "yraj46a46an43", "yreilof", "yroid", "yspend", "yt6erya4646yf", "yugasandrika", "yui", "yuurok", "yuuywil", "yxzx", "yy-h2.nut", "yyhmail", "yyj295r31", "yyolf", "yyt.resolution4print", "yytv.ddns", "z-mail", "z-mild", "z0d", "z1p", "z7az14m", "z7az14m.com", "z86", "za", "zain", "zainmax", "zaktouni", "zane", "zanichelli", "zasod", "zasve", "zavio", "ze", "ze.gally", "zebins", "zebra", "zebua", "zebuaboy",
  "zebuasadis", "zehnminuten", "zehnminutenmail", "zepp", "zer-0", "zeromail", "zesta", "zeta-telecom", "zetmail", "zfymail", "zhcne", "zhorachu", "zhouemail.510520", "zik", "zimbail", "zipcad", "zippymail", "zipsendtest", "zipzaprap.beerolympics", "zipzaps", "ziyap", "zmail.info", "zoaxe", "zoemail", "zoetropes", "zombie-hive", "zomg", "zonamail", "zp", "zrmail", "zumpul", "zumrotin", "zxcv", "zxcvbnm", "zxcxc", "zymail", "zzi", "zzz")


 final val MAJORDOMAINS = Array[String]("aol", "att", "comcast", "facebook", "gmail", "gmx", "googlemail", "google", "hotmail", "hotmail.co",
  "mac", "me", "mail", "msn", "live", "sbcglobal", "verizon", "yahoo", "yahoo.co", "email",
  "fastmail", "games", "hush", "hushmail", "icloud", "iname", "inbox", "lavabit", "love", "outlook",
  "pobox", "protonmail", "rocketmail", "safe-mail", "wow", "ygm", "ymail", "zoho", "yandex", "bellsouth",
  "charter", "cox", "earthlink", "juno", "btinternet", "virginmedia", "blueyonder.co", "freeserve.co", "live.co", "ntlworld",
  "o2.co", "orange", "sky", "talktalk.co", "tiscali.co", "virgin", "wanadoo.co", "bt", "sina", "qq",
  "naver", "hanmail", "daum", "nate", "yahoo.com", "laposte", "wanadoo", "sfr", "neuf", "free",
  "online", "t-online", "web", "libero", "virgilio", "tiscali", "alice", "tin", "poste", "teletu",
  "rambler", "ya", "list", "skynet", "voo", "tvcablenet", "telenet", "hotmail.com", "live.com", "fibertel.com",
  "speedy.com", "arnet.com", "prodigy.net", "outlook.com", "uol.com", "bol.com", "terra.com", "ig.com", "itelefonica.com", "r7",
  "zipmail.com", "globo", "globomail", "oi.com")

  final val COMPLIMENTARYWORDS = Array[String]("affectionately", "best", "best regards", "best wishes", "best", "bgif", "cheers", "ciao", "cordially", "cordially yours",
    "cordially", "fond regards", "kind regards", "many thanks", "my best", "regards", "respectfully yours", "respectfully", "sent from my iphone ", "sincerely",
    "sincerely yours", "sincerely", "talk soon", "thank you", "thank you", "thanking you", "thanks", "thankyou", "very truly yours", "warm regards", "warm regards",
    "warm wishes", "warmly", "with appreciation", "with gratitude", "with sincere appreciation", "with sincere thanks", "with thanks", "yours respectfully", "yours sincerely", "yours truly", "thanks and regards",
    "thanks & regards").map(_.toLowerCase.trim).sortWith( _.length > _.length )
}
